backend:
  name: github
  repo: alphaiotanupes1931/alphaiotanupes1931.github.io
  branch: main
  auth_endpoint: https://decap-cms-oauth-provider.netlify.app/auth
  base_url: https://decap-cms-oauth-provider.netlify.app
  client_id: Ov23liDSptLoonsucuDD

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "."
    create: true
    extension: "html"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
