backend:
  name: github
  repo: alphaiotanupes1931/alphaiotanupes1931.github.io
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

local_backend: true

collections:
  - name: "pages"
    label: "Pages"
    folder: "."
    create: true
    extension: "html"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
